const double COAL_LOWER_HEATING_VALUE = 20.47;
const double COAL_LIGHT_ASH_CONTENT = 0.8;
const double COAL_ASH_MASS_CONTENT = 25.2;
const double COAL_COMBUSTIBLE_MASS_CONTENT = 1.5;
const double COAL_CLEANING_EFFICIENCY = 0.985;

const double FUEL_OIL_LOWER_HEATING_VALUE = 40.4;
const double FUEL_OIL_LIGHT_ASH_CONTENT = 1.0;
const double FUEL_ASH_MASS_CONTENT = 0.15;
const double FUEL_OIL_COMPONENT_PERCENTAGE_G = 0.0;
const double FUEL_OIL_CLEANING_EFFICIENCY = 0.985;
